// Every piece of text on the cost calculator pages (see CostCalculator.jsx),
// in the same five languages as the home page. Each occasion's `cats` list is
// [title, subtitle, [item names]] in the same order as its `perGuest` flags in
// CostCalculator.jsx's OCCASIONS. The strings the PDF uses (see pdfKeys in
// CostCalculator.jsx) stay within Latin-1 for en/fr/es so the built-in PDF
// fonts can draw them.

export const CALC_TEXT = {
  en: {
    ui: {
      eyebrow: "Free budget planner",
      pickTitle: "What are you planning?",
      pickBody: "Pick your occasion to open its cost calculator. It's free, nothing to sign up for, and you can print it or save it as a PDF.",
      intro: "Add the prices you've received, adjust quantities, and see your total as you plan. Print it or save it as a PDF when you're done.",
      guestTitle: "Start with your guest count",
      guestHint: "Items marked \"per guest\" use this number automatically.",
      guestLabel: "Number of guests",
      eg: "e.g.",
      yourEstimate: "Your estimate",
      planByCategory: "Plan by category",
      clearAll: "Clear all",
      clearConfirm: "Clear every price and start over?",
      amountsIn: "All amounts in USD",
      item: "Item", qty: "Qty", costEach: "Cost each", total: "Total",
      perGuest: "per guest",
      guestsPill: "Guests",
      usesGuestCount: "Uses your guest count",
      addCost: "Add a cost",
      customPh: "What's the cost for?",
      remove: "Remove this cost",
      liveEstimate: "Live estimate",
      yourTotal: "Your estimated total",
      perGuestFor: "About {amount} per guest for {n} guests.",
      addGuestsHint: "Add your guest count to see the cost per guest.",
      enterPrice: "Enter a price to build your estimate.",
      savePdf: "Save PDF", saving: "Saving…", print: "Print",
      byCategory: "By category",
      disclaimer: "Prices come from you. This calculator does not include vendor rates or a final quote.",
      estimatedTotal: "Estimated total",
      ctaTitle: "Send the invitation, too",
      ctaBody: "A digital invitation guests open on their phone, with your photos, music, directions and RSVP, all in one link you share on WhatsApp.",
      ctaCreate: "Create your invitation", ctaDesigns: "See the designs",
      home: "Home", designs: "Designs", create: "Create an invitation", privacy: "Privacy Policy", language: "Language",
      prepared: "Prepared {date}",
      guestsN: "{n} guests",
      aboutPerGuest: "About {amount} per guest",
      noPrices: "No prices entered yet.",
      pdfNote: "Prices come from you. This is an estimate, not a vendor quote.",
      otherCost: "Other cost",
      pickPageTitle: "Free Event Cost Calculator",
      metaPick: "Free cost calculator for weddings, birthdays, quinceañeras, baptisms, baby showers and parties. Add your prices, see the total, print it or save it as a PDF.",
      metaOccasion: "{title}: add the prices you've received and watch your budget add up. Free, and you can print it or save it as a PDF.",
    },
    occasions: {
      wedding: { name: "Wedding", title: "Wedding cost calculator", cats: [
        ["Venue & food", "The setting and the menu", ["Venue rental", "Catering", "Drinks"]],
        ["Flowers & décor", "The look of the celebration", ["Flowers", "Décor & lighting"]],
        ["Photo & video", "The moments you keep", ["Photographer", "Videographer"]],
        ["Attire & beauty", "Getting ready for the day", ["Wedding attire", "Hair & makeup"]],
        ["Music & entertainment", "Sound and celebration", ["DJ or band", "Entertainment"]],
        ["Invitations & details", "The finishing touches", ["Invitations", "Guest favors", "Cake"]],
        ["Services & extras", "Everything else to plan", ["Wedding planner", "Transport", "Other costs"]],
      ] },
      birthday: { name: "Birthday", title: "Birthday cost calculator", cats: [
        ["Venue & food", "Where you celebrate and what you serve", ["Venue rental", "Food", "Drinks"]],
        ["Cake & sweets", "The sweetest part", ["Birthday cake", "Sweet table"]],
        ["Decorations", "Setting the party mood", ["Balloons", "Theme décor", "Flowers"]],
        ["Entertainment", "Music, games and fun", ["DJ or music", "Entertainer or activities", "Games & rentals"]],
        ["Photo & video", "Remember the day", ["Photographer", "Photo booth"]],
        ["Invitations & favors", "Before and after the party", ["Invitations", "Party favors"]],
        ["Extras", "Everything else", ["Outfit", "Party planner", "Other costs"]],
      ] },
      quinceanera: { name: "Quinceañera", title: "Quinceañera cost calculator", cats: [
        ["Venue & food", "The reception and the menu", ["Venue rental", "Catering", "Drinks"]],
        ["Dress & beauty", "Her look for the day", ["Quinceañera dress", "Hair & makeup", "Shoes & accessories"]],
        ["Ceremony & traditions", "Mass and the traditions", ["Mass / ceremony", "Tiara & traditional gifts", "Court of honor"]],
        ["Flowers & décor", "The look of the celebration", ["Flowers", "Décor & lighting"]],
        ["Music & dance", "The waltz and the party", ["DJ or band", "Waltz choreography"]],
        ["Photo & video", "The moments you keep", ["Photographer", "Videographer"]],
        ["Cake, invitations & favors", "The finishing touches", ["Cake", "Invitations", "Favors"]],
        ["Extras", "Everything else to plan", ["Party planner", "Transport", "Other costs"]],
      ] },
      baptism: { name: "Baptism", title: "Baptism cost calculator", cats: [
        ["Church & ceremony", "The baptism itself", ["Church fees & offering", "Candle & baptism set"]],
        ["Reception venue & food", "Celebrating afterwards", ["Venue rental", "Food", "Drinks"]],
        ["Outfits", "Dressed for the day", ["Baptism outfit", "Family outfits"]],
        ["Décor & flowers", "The look of the day", ["Flowers", "Décor", "Balloons"]],
        ["Cake & sweets", "Something sweet", ["Cake", "Dragées & favors"]],
        ["Photo & video", "Remember the day", ["Photographer", "Videographer"]],
        ["Invitations & extras", "Everything else", ["Invitations", "Entertainment", "Other costs"]],
      ] },
      babyShower: { name: "Baby Shower", title: "Baby shower cost calculator", cats: [
        ["Venue & food", "Where you gather and what you serve", ["Venue rental", "Food", "Drinks"]],
        ["Cake & sweets", "The sweet table", ["Cake", "Dessert table"]],
        ["Decorations", "The theme and the mood", ["Balloons", "Theme décor", "Flowers"]],
        ["Games & activities", "Fun for the guests", ["Games & prizes", "Entertainment"]],
        ["Photo", "Remember the day", ["Photographer"]],
        ["Invitations & favors", "Before and after", ["Invitations", "Favors"]],
        ["Extras", "Everything else", ["Outfit", "Party planner", "Other costs"]],
      ] },
      party: { name: "Party", title: "Party cost calculator", cats: [
        ["Venue & food", "Where you celebrate and what you serve", ["Venue rental", "Food", "Drinks"]],
        ["Décor", "Setting the mood", ["Decorations", "Flowers", "Lighting"]],
        ["Music & entertainment", "Sound and fun", ["DJ or music", "Entertainment"]],
        ["Photo & video", "Remember the night", ["Photographer", "Videographer"]],
        ["Cake & sweets", "Something sweet", ["Cake", "Sweets"]],
        ["Invitations & favors", "Before and after", ["Invitations", "Favors"]],
        ["Extras", "Everything else", ["Rentals", "Transport", "Other costs"]],
      ] },
    },
  },

  ar: {
    ui: {
      eyebrow: "مخطّط ميزانية مجاني",
      pickTitle: "ما المناسبة التي تخطّط لها؟",
      pickBody: "اختر مناسبتك لتفتح حاسبة تكاليفها. مجانية ومن دون تسجيل، ويمكنك طباعتها أو حفظها كملف PDF.",
      intro: "أضف الأسعار التي حصلت عليها، وعدّل الكميات، وشاهد المجموع أثناء التخطيط. اطبعه أو احفظه كملف PDF عندما تنتهي.",
      guestTitle: "ابدأ بعدد الضيوف",
      guestHint: "البنود المكتوب عليها «لكل ضيف» تستخدم هذا الرقم تلقائياً.",
      guestLabel: "عدد الضيوف",
      eg: "مثلاً",
      yourEstimate: "تقديرك",
      planByCategory: "خطّط حسب الفئة",
      clearAll: "مسح الكل",
      clearConfirm: "هل تريد مسح كل الأسعار والبدء من جديد؟",
      amountsIn: "كل المبالغ بالدولار الأمريكي",
      item: "البند", qty: "الكمية", costEach: "سعر الوحدة", total: "المجموع",
      perGuest: "لكل ضيف",
      guestsPill: "الضيوف",
      usesGuestCount: "يستخدم عدد الضيوف",
      addCost: "إضافة تكلفة",
      customPh: "ما هذه التكلفة؟",
      remove: "حذف هذه التكلفة",
      liveEstimate: "التقدير المباشر",
      yourTotal: "مجموعك التقديري",
      perGuestFor: "حوالي {amount} لكل ضيف لـ {n} ضيفاً.",
      addGuestsHint: "أضف عدد الضيوف لترى التكلفة لكل ضيف.",
      enterPrice: "أدخل سعراً لتبدأ تقديرك.",
      savePdf: "حفظ PDF", saving: "جارٍ الحفظ…", print: "طباعة",
      byCategory: "حسب الفئة",
      disclaimer: "الأسعار من إدخالك. هذه الحاسبة لا تتضمن أسعار المورّدين ولا عرض سعر نهائياً.",
      estimatedTotal: "المجموع التقديري",
      ctaTitle: "وأرسل الدعوة أيضاً",
      ctaBody: "دعوة رقمية يفتحها ضيوفك على هواتفهم، مع صورك وموسيقاك والاتجاهات وتأكيد الحضور، كلها في رابط واحد ترسله على واتساب.",
      ctaCreate: "أنشئ دعوتك", ctaDesigns: "تصفّح التصاميم",
      home: "الرئيسية", designs: "التصاميم", create: "أنشئ دعوة", privacy: "سياسة الخصوصية", language: "اللغة",
      prepared: "أُعدّ في {date}",
      guestsN: "{n} ضيفاً",
      aboutPerGuest: "حوالي {amount} لكل ضيف",
      noPrices: "لم تُدخل أي أسعار بعد.",
      pdfNote: "الأسعار من إدخالك. هذا تقدير وليس عرض سعر من المورّدين.",
      otherCost: "تكلفة أخرى",
      pickPageTitle: "حاسبة تكاليف المناسبات المجانية",
      metaPick: "حاسبة تكاليف مجانية للأعراس وأعياد الميلاد وحفلات الخامسة عشرة والمعموديات وحفلات استقبال المولود والحفلات. أضف أسعارك وشاهد المجموع، واطبعه أو احفظه كملف PDF.",
      metaOccasion: "{title}: أضف الأسعار التي حصلت عليها وشاهد ميزانيتك تتجمّع. مجانية، ويمكنك طباعتها أو حفظها كملف PDF.",
    },
    occasions: {
      wedding: { name: "زفاف", title: "حاسبة تكاليف الزفاف", cats: [
        ["المكان والطعام", "القاعة وقائمة الطعام", ["إيجار القاعة", "الضيافة والطعام", "المشروبات"]],
        ["الزهور والديكور", "إطلالة الاحتفال", ["الزهور", "الديكور والإضاءة"]],
        ["التصوير والفيديو", "لحظات تبقى معك", ["المصوّر", "مصوّر الفيديو"]],
        ["الأزياء والتجميل", "التحضير ليوم الزفاف", ["فستان وبدلة الزفاف", "الشعر والمكياج"]],
        ["الموسيقى والترفيه", "الأجواء والاحتفال", ["دي جي أو فرقة", "الترفيه"]],
        ["الدعوات والتفاصيل", "اللمسات الأخيرة", ["الدعوات", "هدايا الضيوف", "قالب الحلوى"]],
        ["الخدمات والإضافات", "كل ما تبقى للتخطيط", ["منظّم الزفاف", "المواصلات", "تكاليف أخرى"]],
      ] },
      birthday: { name: "عيد ميلاد", title: "حاسبة تكاليف عيد الميلاد", cats: [
        ["المكان والطعام", "مكان الاحتفال وما تقدّمه", ["إيجار المكان", "الطعام", "المشروبات"]],
        ["الكيك والحلويات", "الجزء الأحلى", ["كيك عيد الميلاد", "طاولة الحلويات"]],
        ["الزينة", "أجواء الحفلة", ["البالونات", "ديكور الحفلة", "الزهور"]],
        ["الترفيه", "موسيقى وألعاب ومرح", ["دي جي أو موسيقى", "منشّط أو نشاطات", "ألعاب ومعدّات"]],
        ["التصوير والفيديو", "ذكرى اليوم", ["المصوّر", "ركن التصوير"]],
        ["الدعوات والتوزيعات", "قبل الحفلة وبعدها", ["الدعوات", "توزيعات الحفلة"]],
        ["إضافات", "كل ما تبقى", ["الملابس", "منظّم الحفلة", "تكاليف أخرى"]],
      ] },
      quinceanera: { name: "حفلة الخامسة عشرة", title: "حاسبة تكاليف حفلة الخامسة عشرة", cats: [
        ["المكان والطعام", "الاستقبال وقائمة الطعام", ["إيجار القاعة", "الضيافة والطعام", "المشروبات"]],
        ["الفستان والتجميل", "إطلالتها في هذا اليوم", ["فستان الحفلة", "الشعر والمكياج", "الحذاء والإكسسوارات"]],
        ["المراسم والتقاليد", "القداس والتقاليد", ["القداس / المراسم", "التاج والهدايا التقليدية", "موكب الشرف"]],
        ["الزهور والديكور", "إطلالة الاحتفال", ["الزهور", "الديكور والإضاءة"]],
        ["الموسيقى والرقص", "رقصة الفالس والحفلة", ["دي جي أو فرقة", "تصميم رقصة الفالس"]],
        ["التصوير والفيديو", "لحظات تبقى معك", ["المصوّر", "مصوّر الفيديو"]],
        ["الكيك والدعوات والتوزيعات", "اللمسات الأخيرة", ["الكيك", "الدعوات", "التوزيعات"]],
        ["إضافات", "كل ما تبقى للتخطيط", ["منظّم الحفلة", "المواصلات", "تكاليف أخرى"]],
      ] },
      baptism: { name: "معمودية", title: "حاسبة تكاليف المعمودية", cats: [
        ["الكنيسة والمراسم", "المعمودية نفسها", ["رسوم الكنيسة والتقدمة", "الشمعة وطقم المعمودية"]],
        ["مكان الاستقبال والطعام", "الاحتفال بعد المعمودية", ["إيجار المكان", "الطعام", "المشروبات"]],
        ["الملابس", "إطلالة اليوم", ["لباس المعمودية", "ملابس العائلة"]],
        ["الديكور والزهور", "أجواء اليوم", ["الزهور", "الديكور", "البالونات"]],
        ["الكيك والحلويات", "لمسة حلوة", ["الكيك", "الملبّس والتوزيعات"]],
        ["التصوير والفيديو", "ذكرى اليوم", ["المصوّر", "مصوّر الفيديو"]],
        ["الدعوات والإضافات", "كل ما تبقى", ["الدعوات", "الترفيه", "تكاليف أخرى"]],
      ] },
      babyShower: { name: "حفل استقبال المولود", title: "حاسبة تكاليف حفل استقبال المولود", cats: [
        ["المكان والطعام", "مكان اللقاء وما تقدّمه", ["إيجار المكان", "الطعام", "المشروبات"]],
        ["الكيك والحلويات", "طاولة الحلويات", ["الكيك", "طاولة الحلويات"]],
        ["الزينة", "الفكرة والأجواء", ["البالونات", "ديكور الحفلة", "الزهور"]],
        ["الألعاب والنشاطات", "مرح للضيوف", ["الألعاب والجوائز", "الترفيه"]],
        ["التصوير", "ذكرى اليوم", ["المصوّر"]],
        ["الدعوات والتوزيعات", "قبل وبعد", ["الدعوات", "التوزيعات"]],
        ["إضافات", "كل ما تبقى", ["الملابس", "منظّم الحفلة", "تكاليف أخرى"]],
      ] },
      party: { name: "حفلة", title: "حاسبة تكاليف الحفلة", cats: [
        ["المكان والطعام", "مكان الاحتفال وما تقدّمه", ["إيجار المكان", "الطعام", "المشروبات"]],
        ["الديكور", "أجواء الحفلة", ["الزينة", "الزهور", "الإضاءة"]],
        ["الموسيقى والترفيه", "الأجواء والمرح", ["دي جي أو موسيقى", "الترفيه"]],
        ["التصوير والفيديو", "ذكرى الليلة", ["المصوّر", "مصوّر الفيديو"]],
        ["الكيك والحلويات", "لمسة حلوة", ["الكيك", "الحلويات"]],
        ["الدعوات والتوزيعات", "قبل وبعد", ["الدعوات", "التوزيعات"]],
        ["إضافات", "كل ما تبقى", ["معدّات مستأجرة", "المواصلات", "تكاليف أخرى"]],
      ] },
    },
  },

  fr: {
    ui: {
      eyebrow: "Planificateur de budget gratuit",
      pickTitle: "Qu'organisez-vous ?",
      pickBody: "Choisissez votre occasion pour ouvrir son calculateur. C'est gratuit, sans inscription, et vous pouvez l'imprimer ou l'enregistrer en PDF.",
      intro: "Ajoutez les prix reçus, ajustez les quantités et suivez votre total au fil de l'organisation. Imprimez-le ou enregistrez-le en PDF à la fin.",
      guestTitle: "Commencez par le nombre d'invités",
      guestHint: "Les postes marqués « par invité » utilisent ce nombre automatiquement.",
      guestLabel: "Nombre d'invités",
      eg: "ex.",
      yourEstimate: "Votre estimation",
      planByCategory: "Budget par catégorie",
      clearAll: "Tout effacer",
      clearConfirm: "Effacer tous les prix et recommencer ?",
      amountsIn: "Montants en USD",
      item: "Poste", qty: "Qté", costEach: "Prix unitaire", total: "Total",
      perGuest: "par invité",
      guestsPill: "Invités",
      usesGuestCount: "Utilise votre nombre d'invités",
      addCost: "Ajouter un coût",
      customPh: "À quoi correspond ce coût ?",
      remove: "Supprimer ce coût",
      liveEstimate: "Estimation en direct",
      yourTotal: "Votre total estimé",
      perGuestFor: "Environ {amount} par invité pour {n} invités.",
      addGuestsHint: "Ajoutez le nombre d'invités pour voir le coût par invité.",
      enterPrice: "Saisissez un prix pour construire votre estimation.",
      savePdf: "Enregistrer en PDF", saving: "Enregistrement…", print: "Imprimer",
      byCategory: "Par catégorie",
      disclaimer: "Les prix viennent de vous. Ce calculateur n'inclut ni tarifs de prestataires ni devis final.",
      estimatedTotal: "Total estimé",
      ctaTitle: "Envoyez aussi l'invitation",
      ctaBody: "Une invitation numérique que vos invités ouvrent sur leur téléphone, avec vos photos, votre musique, l'itinéraire et le RSVP, dans un seul lien à partager sur WhatsApp.",
      ctaCreate: "Créer votre invitation", ctaDesigns: "Voir les modèles",
      home: "Accueil", designs: "Modèles", create: "Créer une invitation", privacy: "Politique de confidentialité", language: "Langue",
      prepared: "Préparé le {date}",
      guestsN: "{n} invités",
      aboutPerGuest: "Environ {amount} par invité",
      noPrices: "Aucun prix saisi pour l'instant.",
      pdfNote: "Les prix viennent de vous. Ceci est une estimation, pas un devis.",
      otherCost: "Autre coût",
      pickPageTitle: "Calculateur de budget gratuit",
      metaPick: "Calculateur de budget gratuit pour mariages, anniversaires, quinceañeras, baptêmes, baby showers et fêtes. Ajoutez vos prix, voyez le total, imprimez-le ou enregistrez-le en PDF.",
      metaOccasion: "{title} : ajoutez les prix reçus et voyez votre budget se construire. Gratuit, à imprimer ou à enregistrer en PDF.",
    },
    occasions: {
      wedding: { name: "Mariage", title: "Calculateur de budget mariage", cats: [
        ["Lieu et repas", "Le cadre et le menu", ["Location de la salle", "Traiteur", "Boissons"]],
        ["Fleurs et décoration", "L'ambiance de la fête", ["Fleurs", "Décoration et éclairage"]],
        ["Photo et vidéo", "Les souvenirs à garder", ["Photographe", "Vidéaste"]],
        ["Tenues et beauté", "Se préparer pour le jour J", ["Tenues de mariage", "Coiffure et maquillage"]],
        ["Musique et animation", "Le son et la fête", ["DJ ou orchestre", "Animation"]],
        ["Faire-part et détails", "Les touches finales", ["Faire-part", "Cadeaux invités", "Gâteau"]],
        ["Services et extras", "Tout le reste", ["Wedding planner", "Transport", "Autres frais"]],
      ] },
      birthday: { name: "Anniversaire", title: "Calculateur de budget anniversaire", cats: [
        ["Lieu et repas", "Où vous fêtez et ce que vous servez", ["Location du lieu", "Repas", "Boissons"]],
        ["Gâteau et douceurs", "La partie la plus sucrée", ["Gâteau d'anniversaire", "Table de douceurs"]],
        ["Décoration", "L'ambiance de la fête", ["Ballons", "Décoration à thème", "Fleurs"]],
        ["Animation", "Musique, jeux et fun", ["DJ ou musique", "Animateur ou activités", "Jeux et locations"]],
        ["Photo et vidéo", "Garder le souvenir", ["Photographe", "Photobooth"]],
        ["Invitations et cadeaux", "Avant et après la fête", ["Invitations", "Petits cadeaux invités"]],
        ["Extras", "Tout le reste", ["Tenue", "Organisateur de fête", "Autres frais"]],
      ] },
      quinceanera: { name: "Quinceañera", title: "Calculateur de budget quinceañera", cats: [
        ["Lieu et repas", "La réception et le menu", ["Location de la salle", "Traiteur", "Boissons"]],
        ["Robe et beauté", "Son look du jour", ["Robe de quinceañera", "Coiffure et maquillage", "Chaussures et accessoires"]],
        ["Cérémonie et traditions", "La messe et les traditions", ["Messe / cérémonie", "Diadème et cadeaux traditionnels", "Cour d'honneur"]],
        ["Fleurs et décoration", "L'ambiance de la fête", ["Fleurs", "Décoration et éclairage"]],
        ["Musique et danse", "La valse et la fête", ["DJ ou orchestre", "Chorégraphie de la valse"]],
        ["Photo et vidéo", "Les souvenirs à garder", ["Photographe", "Vidéaste"]],
        ["Gâteau, invitations et cadeaux", "Les touches finales", ["Gâteau", "Invitations", "Petits cadeaux"]],
        ["Extras", "Tout le reste", ["Organisateur de fête", "Transport", "Autres frais"]],
      ] },
      baptism: { name: "Baptême", title: "Calculateur de budget baptême", cats: [
        ["Église et cérémonie", "Le baptême lui-même", ["Frais d'église et offrande", "Cierge et coffret de baptême"]],
        ["Réception et repas", "La fête après la cérémonie", ["Location du lieu", "Repas", "Boissons"]],
        ["Tenues", "Habillés pour le jour J", ["Tenue de baptême", "Tenues de la famille"]],
        ["Décoration et fleurs", "L'ambiance du jour", ["Fleurs", "Décoration", "Ballons"]],
        ["Gâteau et douceurs", "Une touche sucrée", ["Gâteau", "Dragées et cadeaux"]],
        ["Photo et vidéo", "Garder le souvenir", ["Photographe", "Vidéaste"]],
        ["Faire-part et extras", "Tout le reste", ["Faire-part", "Animation", "Autres frais"]],
      ] },
      babyShower: { name: "Baby shower", title: "Calculateur de budget baby shower", cats: [
        ["Lieu et repas", "Où vous vous retrouvez et ce que vous servez", ["Location du lieu", "Repas", "Boissons"]],
        ["Gâteau et douceurs", "La table sucrée", ["Gâteau", "Table de desserts"]],
        ["Décoration", "Le thème et l'ambiance", ["Ballons", "Décoration à thème", "Fleurs"]],
        ["Jeux et activités", "Du fun pour les invités", ["Jeux et lots", "Animation"]],
        ["Photo", "Garder le souvenir", ["Photographe"]],
        ["Invitations et cadeaux", "Avant et après", ["Invitations", "Petits cadeaux"]],
        ["Extras", "Tout le reste", ["Tenue", "Organisateur de fête", "Autres frais"]],
      ] },
      party: { name: "Fête", title: "Calculateur de budget fête", cats: [
        ["Lieu et repas", "Où vous fêtez et ce que vous servez", ["Location du lieu", "Repas", "Boissons"]],
        ["Décoration", "L'ambiance", ["Décoration", "Fleurs", "Éclairage"]],
        ["Musique et animation", "Le son et le fun", ["DJ ou musique", "Animation"]],
        ["Photo et vidéo", "Garder le souvenir de la soirée", ["Photographe", "Vidéaste"]],
        ["Gâteau et douceurs", "Une touche sucrée", ["Gâteau", "Douceurs"]],
        ["Invitations et cadeaux", "Avant et après", ["Invitations", "Petits cadeaux"]],
        ["Extras", "Tout le reste", ["Locations", "Transport", "Autres frais"]],
      ] },
    },
  },

  es: {
    ui: {
      eyebrow: "Planificador de presupuesto gratis",
      pickTitle: "¿Qué estás planeando?",
      pickBody: "Elige tu ocasión para abrir su calculadora. Es gratis, sin registrarte, y puedes imprimirla o guardarla en PDF.",
      intro: "Añade los precios que te dieron, ajusta las cantidades y mira tu total mientras planeas. Imprímelo o guárdalo en PDF cuando termines.",
      guestTitle: "Empieza con el número de invitados",
      guestHint: "Los conceptos marcados «por invitado» usan este número automáticamente.",
      guestLabel: "Número de invitados",
      eg: "p. ej.",
      yourEstimate: "Tu estimación",
      planByCategory: "Presupuesto por categoría",
      clearAll: "Borrar todo",
      clearConfirm: "¿Borrar todos los precios y empezar de nuevo?",
      amountsIn: "Montos en USD",
      item: "Concepto", qty: "Cant.", costEach: "Precio unitario", total: "Total",
      perGuest: "por invitado",
      guestsPill: "Invitados",
      usesGuestCount: "Usa tu número de invitados",
      addCost: "Añadir un gasto",
      customPh: "¿Para qué es este gasto?",
      remove: "Quitar este gasto",
      liveEstimate: "Estimación en vivo",
      yourTotal: "Tu total estimado",
      perGuestFor: "Unos {amount} por invitado para {n} invitados.",
      addGuestsHint: "Añade el número de invitados para ver el costo por invitado.",
      enterPrice: "Escribe un precio para armar tu estimación.",
      savePdf: "Guardar PDF", saving: "Guardando…", print: "Imprimir",
      byCategory: "Por categoría",
      disclaimer: "Los precios los pones tú. Esta calculadora no incluye tarifas de proveedores ni una cotización final.",
      estimatedTotal: "Total estimado",
      ctaTitle: "Envía también la invitación",
      ctaBody: "Una invitación digital que tus invitados abren en el teléfono, con tus fotos, música, cómo llegar y confirmación, todo en un enlace que compartes por WhatsApp.",
      ctaCreate: "Crea tu invitación", ctaDesigns: "Ver los diseños",
      home: "Inicio", designs: "Diseños", create: "Crear una invitación", privacy: "Política de privacidad", language: "Idioma",
      prepared: "Preparado el {date}",
      guestsN: "{n} invitados",
      aboutPerGuest: "Unos {amount} por invitado",
      noPrices: "Todavía no hay precios.",
      pdfNote: "Los precios los pones tú. Es una estimación, no una cotización de proveedores.",
      otherCost: "Otro gasto",
      pickPageTitle: "Calculadora de gastos gratis",
      metaPick: "Calculadora de gastos gratis para bodas, cumpleaños, quinceañeras, bautizos, baby showers y fiestas. Añade tus precios, mira el total, imprímelo o guárdalo en PDF.",
      metaOccasion: "{title}: añade los precios que te dieron y mira cómo suma tu presupuesto. Gratis, para imprimir o guardar en PDF.",
    },
    occasions: {
      wedding: { name: "Boda", title: "Calculadora de gastos de boda", cats: [
        ["Lugar y comida", "El lugar y el menú", ["Alquiler del salón", "Catering", "Bebidas"]],
        ["Flores y decoración", "El estilo de la celebración", ["Flores", "Decoración e iluminación"]],
        ["Foto y video", "Los momentos que guardas", ["Fotógrafo", "Videógrafo"]],
        ["Vestuario y belleza", "Listos para el gran día", ["Vestido y traje", "Peinado y maquillaje"]],
        ["Música y entretenimiento", "Música y celebración", ["DJ o banda", "Entretenimiento"]],
        ["Invitaciones y detalles", "Los toques finales", ["Invitaciones", "Recuerdos para invitados", "Pastel"]],
        ["Servicios y extras", "Todo lo demás", ["Wedding planner", "Transporte", "Otros gastos"]],
      ] },
      birthday: { name: "Cumpleaños", title: "Calculadora de gastos de cumpleaños", cats: [
        ["Lugar y comida", "Dónde celebras y qué sirves", ["Alquiler del lugar", "Comida", "Bebidas"]],
        ["Pastel y dulces", "La parte más dulce", ["Pastel de cumpleaños", "Mesa de dulces"]],
        ["Decoración", "El ambiente de la fiesta", ["Globos", "Decoración temática", "Flores"]],
        ["Entretenimiento", "Música, juegos y diversión", ["DJ o música", "Animador o actividades", "Juegos y alquileres"]],
        ["Foto y video", "Recuerda el día", ["Fotógrafo", "Fotomatón"]],
        ["Invitaciones y recuerdos", "Antes y después de la fiesta", ["Invitaciones", "Recuerdos de la fiesta"]],
        ["Extras", "Todo lo demás", ["Ropa", "Organizador de fiestas", "Otros gastos"]],
      ] },
      quinceanera: { name: "Quinceañera", title: "Calculadora de gastos de quinceañera", cats: [
        ["Lugar y comida", "La recepción y el menú", ["Alquiler del salón", "Catering", "Bebidas"]],
        ["Vestido y belleza", "Su look para el día", ["Vestido de quinceañera", "Peinado y maquillaje", "Zapatos y accesorios"]],
        ["Ceremonia y tradiciones", "La misa y las tradiciones", ["Misa / ceremonia", "Tiara y regalos tradicionales", "Corte de honor"]],
        ["Flores y decoración", "El estilo de la celebración", ["Flores", "Decoración e iluminación"]],
        ["Música y baile", "El vals y la fiesta", ["DJ o banda", "Coreografía del vals"]],
        ["Foto y video", "Los momentos que guardas", ["Fotógrafo", "Videógrafo"]],
        ["Pastel, invitaciones y recuerdos", "Los toques finales", ["Pastel", "Invitaciones", "Recuerdos"]],
        ["Extras", "Todo lo demás", ["Organizador de fiestas", "Transporte", "Otros gastos"]],
      ] },
      baptism: { name: "Bautizo", title: "Calculadora de gastos de bautizo", cats: [
        ["Iglesia y ceremonia", "El bautizo en sí", ["Gastos de la iglesia y ofrenda", "Vela y set de bautizo"]],
        ["Recepción y comida", "La celebración después", ["Alquiler del lugar", "Comida", "Bebidas"]],
        ["Vestuario", "Vestidos para el día", ["Ropa de bautizo", "Ropa de la familia"]],
        ["Decoración y flores", "El ambiente del día", ["Flores", "Decoración", "Globos"]],
        ["Pastel y dulces", "Algo dulce", ["Pastel", "Peladillas y recuerdos"]],
        ["Foto y video", "Recuerda el día", ["Fotógrafo", "Videógrafo"]],
        ["Invitaciones y extras", "Todo lo demás", ["Invitaciones", "Entretenimiento", "Otros gastos"]],
      ] },
      babyShower: { name: "Baby shower", title: "Calculadora de gastos de baby shower", cats: [
        ["Lugar y comida", "Dónde se reúnen y qué sirves", ["Alquiler del lugar", "Comida", "Bebidas"]],
        ["Pastel y dulces", "La mesa dulce", ["Pastel", "Mesa de postres"]],
        ["Decoración", "El tema y el ambiente", ["Globos", "Decoración temática", "Flores"]],
        ["Juegos y actividades", "Diversión para los invitados", ["Juegos y premios", "Entretenimiento"]],
        ["Foto", "Recuerda el día", ["Fotógrafo"]],
        ["Invitaciones y recuerdos", "Antes y después", ["Invitaciones", "Recuerdos"]],
        ["Extras", "Todo lo demás", ["Ropa", "Organizador de fiestas", "Otros gastos"]],
      ] },
      party: { name: "Fiesta", title: "Calculadora de gastos de fiesta", cats: [
        ["Lugar y comida", "Dónde celebras y qué sirves", ["Alquiler del lugar", "Comida", "Bebidas"]],
        ["Decoración", "El ambiente", ["Decoración", "Flores", "Iluminación"]],
        ["Música y entretenimiento", "Música y diversión", ["DJ o música", "Entretenimiento"]],
        ["Foto y video", "Recuerda la noche", ["Fotógrafo", "Videógrafo"]],
        ["Pastel y dulces", "Algo dulce", ["Pastel", "Dulces"]],
        ["Invitaciones y recuerdos", "Antes y después", ["Invitaciones", "Recuerdos"]],
        ["Extras", "Todo lo demás", ["Alquileres", "Transporte", "Otros gastos"]],
      ] },
    },
  },

  hy: {
    ui: {
      eyebrow: "Անվճար բյուջեի պլանավորիչ",
      pickTitle: "Ի՞նչ եք պլանավորում",
      pickBody: "Ընտրեք ձեր առիթը՝ դրա ծախսերի հաշվիչը բացելու համար։ Անվճար է, առանց գրանցման, և կարող եք տպել այն կամ պահել որպես PDF։",
      intro: "Ավելացրեք ստացած գները, ճշտեք քանակները և հետևեք ընդհանուր գումարին պլանավորելիս։ Ավարտելուց հետո տպեք կամ պահեք որպես PDF։",
      guestTitle: "Սկսեք հյուրերի թվից",
      guestHint: "«Մեկ հյուրի համար» նշված կետերը ավտոմատ օգտագործում են այս թիվը։",
      guestLabel: "Հյուրերի թիվը",
      eg: "օր.՝",
      yourEstimate: "Ձեր նախահաշիվը",
      planByCategory: "Պլանավորում ըստ բաժինների",
      clearAll: "Մաքրել բոլորը",
      clearConfirm: "Մաքրե՞լ բոլոր գները և սկսել նորից",
      amountsIn: "Բոլոր գումարները ԱՄՆ դոլարով",
      item: "Կետ", qty: "Քանակ", costEach: "Միավորի գին", total: "Ընդամենը",
      perGuest: "մեկ հյուրի համար",
      guestsPill: "Հյուրեր",
      usesGuestCount: "Օգտագործում է հյուրերի թիվը",
      addCost: "Ավելացնել ծախս",
      customPh: "Ինչի՞ ծախս է",
      remove: "Հեռացնել այս ծախսը",
      liveEstimate: "Ընթացիկ նախահաշիվ",
      yourTotal: "Ձեր նախահաշվային գումարը",
      perGuestFor: "Մոտ {amount} մեկ հյուրի համար՝ {n} հյուրի դեպքում։",
      addGuestsHint: "Ավելացրեք հյուրերի թիվը՝ մեկ հյուրի արժեքը տեսնելու համար։",
      enterPrice: "Մուտքագրեք գին՝ նախահաշիվը կազմելու համար։",
      savePdf: "Պահել PDF", saving: "Պահվում է…", print: "Տպել",
      byCategory: "Ըստ բաժինների",
      disclaimer: "Գները ձերն են։ Այս հաշվիչը չի ներառում մատակարարների գներ կամ վերջնական առաջարկ։",
      estimatedTotal: "Նախահաշվային գումար",
      ctaTitle: "Ուղարկեք նաև հրավերը",
      ctaBody: "Թվային հրավեր, որը հյուրերը բացում են իրենց հեռախոսով՝ ձեր լուսանկարներով, երաժշտությամբ, ուղղություններով և RSVP-ով, մեկ հղումով, որը կիսում եք WhatsApp-ով։",
      ctaCreate: "Ստեղծեք ձեր հրավերը", ctaDesigns: "Դիտել դիզայնները",
      home: "Գլխավոր", designs: "Դիզայններ", create: "Ստեղծել հրավեր", privacy: "Գաղտնիության քաղաքականություն", language: "Լեզու",
      prepared: "Պատրաստված է՝ {date}",
      guestsN: "{n} հյուր",
      aboutPerGuest: "Մոտ {amount} մեկ հյուրի համար",
      noPrices: "Գներ դեռ չկան։",
      pdfNote: "Գները ձերն են։ Սա նախահաշիվ է, ոչ թե մատակարարի առաջարկ։",
      otherCost: "Այլ ծախս",
      pickPageTitle: "Անվճար ծախսերի հաշվիչ",
      metaPick: "Անվճար ծախսերի հաշվիչ հարսանիքների, ծննդյան տոների, տասնհինգամյակների, մկրտությունների, baby shower-ների և խնջույքների համար։ Ավելացրեք գները, տեսեք ընդհանուր գումարը, տպեք կամ պահեք որպես PDF։",
      metaOccasion: "{title}. ավելացրեք ստացած գները և տեսեք ձեր բյուջեն։ Անվճար է, կարող եք տպել կամ պահել որպես PDF։",
    },
    occasions: {
      wedding: { name: "Հարսանիք", title: "Հարսանիքի ծախսերի հաշվիչ", cats: [
        ["Սրահ և սնունդ", "Վայրը և ճաշացանկը", ["Սրահի վարձ", "Սնունդ (քեյթրինգ)", "Խմիչքներ"]],
        ["Ծաղիկներ և ձևավորում", "Տոնակատարության տեսքը", ["Ծաղիկներ", "Ձևավորում և լուսավորություն"]],
        ["Լուսանկար և տեսանկար", "Պահեր, որոնք մնում են", ["Լուսանկարիչ", "Տեսանկարահանող"]],
        ["Հագուստ և գեղեցկություն", "Պատրաստվելով օրվան", ["Հարսանեկան հագուստ", "Սանրվածք և դիմահարդարում"]],
        ["Երաժշտություն և զվարճանք", "Երաժշտություն և տոն", ["DJ կամ նվագախումբ", "Զվարճանք"]],
        ["Հրավերներ և մանրուքներ", "Վերջնական հպումներ", ["Հրավերներ", "Նվերներ հյուրերին", "Տորթ"]],
        ["Ծառայություններ և այլ", "Մնացած ամեն ինչ", ["Հարսանիքի կազմակերպիչ", "Տրանսպորտ", "Այլ ծախսեր"]],
      ] },
      birthday: { name: "Ծննդյան տոն", title: "Ծննդյան տոնի ծախսերի հաշվիչ", cats: [
        ["Վայր և սնունդ", "Որտեղ եք նշում և ինչ եք հյուրասիրում", ["Վայրի վարձ", "Սնունդ", "Խմիչքներ"]],
        ["Տորթ և քաղցրավենիք", "Ամենաքաղցր մասը", ["Ծննդյան տորթ", "Քաղցրավենիքի սեղան"]],
        ["Ձևավորում", "Տոնի տրամադրությունը", ["Փուչիկներ", "Թեմատիկ ձևավորում", "Ծաղիկներ"]],
        ["Զվարճանք", "Երաժշտություն, խաղեր և ուրախություն", ["DJ կամ երաժշտություն", "Անիմատոր կամ միջոցառումներ", "Խաղեր և վարձույթ"]],
        ["Լուսանկար և տեսանկար", "Հիշեք այդ օրը", ["Լուսանկարիչ", "Ֆոտոխցիկ"]],
        ["Հրավերներ և նվերներ", "Տոնից առաջ և հետո", ["Հրավերներ", "Նվերներ հյուրերին"]],
        ["Այլ", "Մնացած ամեն ինչ", ["Հագուստ", "Տոնի կազմակերպիչ", "Այլ ծախսեր"]],
      ] },
      quinceanera: { name: "Տասնհինգամյակ", title: "Տասնհինգամյակի ծախսերի հաշվիչ", cats: [
        ["Սրահ և սնունդ", "Ընդունելությունը և ճաշացանկը", ["Սրահի վարձ", "Սնունդ (քեյթրինգ)", "Խմիչքներ"]],
        ["Զգեստ և գեղեցկություն", "Նրա կերպարը այդ օրը", ["Տոնական զգեստ", "Սանրվածք և դիմահարդարում", "Կոշիկներ և աքսեսուարներ"]],
        ["Արարողություն և ավանդույթներ", "Պատարագը և ավանդույթները", ["Պատարագ / արարողություն", "Թագ և ավանդական նվերներ", "Պատվո շքախումբ"]],
        ["Ծաղիկներ և ձևավորում", "Տոնակատարության տեսքը", ["Ծաղիկներ", "Ձևավորում և լուսավորություն"]],
        ["Երաժշտություն և պար", "Վալսը և տոնը", ["DJ կամ նվագախումբ", "Վալսի բեմադրություն"]],
        ["Լուսանկար և տեսանկար", "Պահեր, որոնք մնում են", ["Լուսանկարիչ", "Տեսանկարահանող"]],
        ["Տորթ, հրավերներ և նվերներ", "Վերջնական հպումներ", ["Տորթ", "Հրավերներ", "Նվերներ հյուրերին"]],
        ["Այլ", "Մնացած ամեն ինչ", ["Տոնի կազմակերպիչ", "Տրանսպորտ", "Այլ ծախսեր"]],
      ] },
      baptism: { name: "Մկրտություն", title: "Մկրտության ծախսերի հաշվիչ", cats: [
        ["Եկեղեցի և արարողություն", "Մկրտությունը", ["Եկեղեցու վճարներ և նվիրատվություն", "Մոմ և մկրտության հավաքածու"]],
        ["Ընդունելության վայր և սնունդ", "Նշում արարողությունից հետո", ["Վայրի վարձ", "Սնունդ", "Խմիչքներ"]],
        ["Հագուստ", "Տոնական տեսք", ["Մկրտության հագուստ", "Ընտանիքի հագուստ"]],
        ["Ձևավորում և ծաղիկներ", "Օրվա տեսքը", ["Ծաղիկներ", "Ձևավորում", "Փուչիկներ"]],
        ["Տորթ և քաղցրավենիք", "Մի քիչ քաղցրություն", ["Տորթ", "Դրաժե և նվերներ"]],
        ["Լուսանկար և տեսանկար", "Հիշեք այդ օրը", ["Լուսանկարիչ", "Տեսանկարահանող"]],
        ["Հրավերներ և այլ", "Մնացած ամեն ինչ", ["Հրավերներ", "Զվարճանք", "Այլ ծախսեր"]],
      ] },
      babyShower: { name: "Baby shower", title: "Baby shower-ի ծախսերի հաշվիչ", cats: [
        ["Վայր և սնունդ", "Որտեղ եք հավաքվում և ինչ եք հյուրասիրում", ["Վայրի վարձ", "Սնունդ", "Խմիչքներ"]],
        ["Տորթ և քաղցրավենիք", "Քաղցր սեղանը", ["Տորթ", "Աղանդերի սեղան"]],
        ["Ձևավորում", "Թեման և տրամադրությունը", ["Փուչիկներ", "Թեմատիկ ձևավորում", "Ծաղիկներ"]],
        ["Խաղեր և միջոցառումներ", "Զվարճանք հյուրերի համար", ["Խաղեր և մրցանակներ", "Զվարճանք"]],
        ["Լուսանկար", "Հիշեք այդ օրը", ["Լուսանկարիչ"]],
        ["Հրավերներ և նվերներ", "Առաջ և հետո", ["Հրավերներ", "Նվերներ հյուրերին"]],
        ["Այլ", "Մնացած ամեն ինչ", ["Հագուստ", "Տոնի կազմակերպիչ", "Այլ ծախսեր"]],
      ] },
      party: { name: "Խնջույք", title: "Խնջույքի ծախսերի հաշվիչ", cats: [
        ["Վայր և սնունդ", "Որտեղ եք նշում և ինչ եք հյուրասիրում", ["Վայրի վարձ", "Սնունդ", "Խմիչքներ"]],
        ["Ձևավորում", "Տրամադրությունը", ["Զարդարանք", "Ծաղիկներ", "Լուսավորություն"]],
        ["Երաժշտություն և զվարճանք", "Երաժշտություն և ուրախություն", ["DJ կամ երաժշտություն", "Զվարճանք"]],
        ["Լուսանկար և տեսանկար", "Հիշեք այդ երեկոն", ["Լուսանկարիչ", "Տեսանկարահանող"]],
        ["Տորթ և քաղցրավենիք", "Մի քիչ քաղցրություն", ["Տորթ", "Քաղցրավենիք"]],
        ["Հրավերներ և նվերներ", "Առաջ և հետո", ["Հրավերներ", "Նվերներ հյուրերին"]],
        ["Այլ", "Մնացած ամեն ինչ", ["Վարձույթ", "Տրանսպորտ", "Այլ ծախսեր"]],
      ] },
    },
  },
};
