// Every piece of text on the home page (and its FAQ, About and Contact
// sections), in the same five languages the invitations support. Feature
// items are in the same order as LANDING_FEATURE_ICONS in App.jsx, and the
// FAQ item with `privacy: true` ends with a link to the Privacy Policy
// (`privacyLink`, followed by `privacyAfter`).

export const LANDING_LANGS = ["en", "ar", "fr", "es", "hy"];

export const LANDING_LANG_NAMES = { en: "English", ar: "العربية", fr: "Français", es: "Español", hy: "Հայերեն" };

export const LANDING_TEXT = {
  en: {
    nav: { how: "How it works", features: "Features", designs: "Designs", blog: "Blog", faq: "FAQ", about: "About", contact: "Contact", logIn: "Log in", start: "Start" },
    hero: {
      eyebrow: "Digital invitations for every occasion",
      title: "An invitation that opens like a real envelope.",
      body: "Create an invitation for your wedding, birthday, quinceañera or any event. Guests tap it open on their phone, with your photos, music, the schedule, directions and RSVP, all in one link you share on WhatsApp.",
      create: "Create your invitation",
      seeDesigns: "See the designs",
      note: "Works on any phone · Nothing for guests to download",
      phoneLink: "Tap the invitation to open it, or view it full screen",
    },
    occasions: {
      title: "One invitation, any occasion",
      body: "Each occasion starts with its own ready-written pages and schedule, which you can change however you like.",
      names: { wedding: "Wedding", birthday: "Birthday", quinceanera: "Quinceañera", baptism: "Baptism", babyShower: "Baby Shower", any: "Any event" },
    },
    how: {
      title: "Three steps, and it's on its way",
      steps: [
        { title: "Pick a design", body: "Start from a ready-made design, or from a blank canvas." },
        { title: "Make it yours", body: "Add your names, photos, music, the day's schedule and venues, and place everything exactly where you want it." },
        { title: "Share and track", body: "Send one link on WhatsApp. See who opened it and who's coming as the replies arrive." },
      ],
    },
    features: {
      title: "Everything the day needs, in one link",
      body: "Each page of the invitation is its own moment. Show the ones you need and hide the rest.",
      items: [
        { title: "An envelope they tap open", body: "A wax seal or envelope guests tap to open, with your own photo or video behind it." },
        { title: "Your song, from the first tap", body: "Background music starts the moment they open the invitation." },
        { title: "RSVP with names", body: "Guests confirm with their names and how many are coming, straight into your guest list." },
        { title: "Schedule and directions", body: "The day's timeline, a live countdown, and one-tap directions to every venue." },
        { title: "Gift registry", body: "Registry links or bank details, shown with the rest of the invitation." },
        { title: "Live stream", body: "Family and friends who can't travel can watch it live, free or paid." },
        { title: "Song requests", body: "Guests send the songs they want to hear straight to your DJ." },
        { title: "Guest networking", body: "Guests discover others who share their interests and connect from their phone before the day." },
        { title: "Voice messages", body: "Guests who can't make it can leave you a recorded voice message with their reply." },
        { title: "QR check-in", body: "Every confirmed guest gets a QR code to check in at the door." },
        { title: "Five languages, translated by AI", body: "Write it once in your language and AI translates the whole invitation into English, Arabic, French, Spanish or Armenian. Guests switch language on the invitation itself." },
        { title: "An AI assistant that fills it in", body: "Tell the assistant your names, date and venues, and it fills in the invitation form for you." },
      ],
    },
    designs: { title: "Designs ready to make yours", body: "Buy a design, then customize it yourself in Canva.", seeAll: "See all designs" },
    dashboard: {
      title: "Your guest list, handled",
      body: "Every reply lands in your own dashboard, so you always know where things stand.",
      points: [
        "See who opened the invitation, and who hasn't yet",
        "Track confirmations and the headcount as replies come in",
        "Plan tables and your venue's seating layout",
        "Send each guest or family their own personal link",
      ],
      label: "Dashboard",
      stats: ["Invited", "Opened", "Coming"],
      rows: [["The Haddad family", "Coming · 4"], ["Rita & Sami", "Opened"], ["The Khoury family", "Coming · 3"], ["Uncle Georges", "Not opened yet"]],
    },
    faq: {
      title: "Frequently Asked Questions",
      body: "Everything you need to know about our digital invitation service.",
      items: [
        { q: "What is a digital invitation?", a: "It's an invitation your guests open on their phone from a single link. They tap an envelope to open it, and inside are your photos, music, the schedule, directions to each venue and an RSVP, all in one place." },
        { q: "Which occasions can I use it for?", a: "Weddings, birthdays, quinceañeras, baptisms, baby showers and any other event. Each occasion starts with its own ready-written pages, which you can change however you like." },
        { q: "Do my guests need to download an app?", a: "No. The invitation opens in the browser on any phone, so there's nothing to install and no account for guests to create." },
        { q: "How do I send it to my guests?", a: "You get one link to share on WhatsApp, Instagram, SMS or email. You can also create a personal link for each family, so their reply is matched to them in your guest list." },
        { q: "How do RSVPs work?", a: "Guests confirm with their names and how many people are coming. Every reply appears straight away in your dashboard, where you can also see who has opened the invitation and set an RSVP deadline." },
        { q: "Can I change the invitation after I've sent it?", a: "Yes. Edit it at any time and save; your guests will see the latest version on the same link." },
        { q: "Which languages are available?", a: "English, Arabic, French, Spanish and Armenian. When you add a language, AI translates the whole invitation for you in seconds, and you can still edit any text by hand. Guests can switch between the languages you turn on, right on the invitation." },
        { q: "Can I add music, photos and video?", a: "Yes. Add background music that starts when the invitation opens, your own photo or video behind the envelope, photo backgrounds on every page, and a live stream for guests who can't attend." },
        { q: "How do I buy a design?", a: "Pick one on the Designs page and pay online. Canva designs are customized in Canva; our website designs are customized directly on eInvite.me after you create your account." },
        { q: "Can I get a refund?", a: "All payments are final and non-refundable. Designs and features are digital and delivered straight away, so we can't refund them once paid. If something isn't working as it should, message us and we'll help put it right." },
        { q: "What happens to my information?", a: "We only use it to run your invitation and support you, and we never sell it. Read the details in our", privacy: true, privacyLink: "Privacy Policy", privacyAfter: "." },
        { q: "How do I get help?", a: "Tap the chat button at the bottom of any page to talk to us directly, or reach us through the Contact section. We're happy to help at every step." },
      ],
    },
    cta: { title: "Ready when you are", body: "Start with a design you love, and send it the same day.", create: "Create your invitation", browse: "Browse the designs" },
    about: {
      title: "About us",
      p1: "eInvite.me is a digital invitation studio based in Beirut, Lebanon. We believe the invitation is the first moment of every celebration, so we make invitations that feel as special to open as the day itself: an envelope your guests tap open, your music, your photos and every detail of the day in one link.",
      p2: "Weddings, birthdays, quinceañeras, baptisms or any gathering you're planning, we're here to help you create it and send it, and we're one message away whenever you need a hand.",
      office: "Our office",
      address: "Office 305, Tower 44, Dekweneh, Beirut, Lebanon",
      openMaps: "Open in Google Maps",
      mapTitle: "eInvite.me office location",
    },
    contact: {
      title: "Contact us",
      bodyChat: "Questions before you start? Message us directly — we're happy to help.",
      bodyNoChat: "Questions before you start? We're happy to help.",
    },
    footer: { privacy: "Privacy Policy" },
    language: "Language",
  },

  ar: {
    nav: { how: "كيف يعمل", features: "المميزات", designs: "التصاميم", blog: "المدونة", faq: "الأسئلة الشائعة", about: "من نحن", contact: "تواصل معنا", logIn: "تسجيل الدخول", start: "ابدأ" },
    hero: {
      eyebrow: "دعوات رقمية لكل مناسبة",
      title: "دعوة تُفتح كظرفٍ حقيقي.",
      body: "أنشئ دعوة لحفل زفافك أو عيد ميلادك أو حفلة الخامسة عشرة أو أي مناسبة. يفتحها ضيوفك بلمسة على هواتفهم، مع صورك وموسيقاك وبرنامج اليوم والاتجاهات وتأكيد الحضور، كلّها في رابط واحد تشاركه عبر واتساب.",
      create: "أنشئ دعوتك",
      seeDesigns: "شاهد التصاميم",
      note: "تعمل على أي هاتف · لا يحتاج الضيوف إلى تنزيل أي شيء",
      phoneLink: "اضغط على الدعوة لفتحها، أو اعرضها بملء الشاشة",
    },
    occasions: {
      title: "دعوة واحدة، لكل مناسبة",
      body: "تبدأ كل مناسبة بصفحات وبرنامج مكتوبين مسبقاً، ويمكنك تعديلها كما تشاء.",
      names: { wedding: "زفاف", birthday: "عيد ميلاد", quinceanera: "حفلة الخامسة عشرة", baptism: "معمودية", babyShower: "حفل استقبال المولود", any: "أي مناسبة" },
    },
    how: {
      title: "ثلاث خطوات، وتصبح في طريقها",
      steps: [
        { title: "اختر تصميماً", body: "ابدأ من تصميم جاهز، أو من صفحة فارغة." },
        { title: "اجعلها خاصة بك", body: "أضف الأسماء والصور والموسيقى وبرنامج اليوم والأماكن، وضع كل شيء حيث تريد تماماً." },
        { title: "شارك وتابع", body: "أرسل رابطاً واحداً عبر واتساب، وتابع من فتحها ومن سيحضر مع وصول الردود." },
      ],
    },
    features: {
      title: "كل ما يحتاجه اليوم، في رابط واحد",
      body: "كل صفحة في الدعوة لحظة قائمة بذاتها. أظهر ما تحتاجه وأخفِ الباقي.",
      items: [
        { title: "ظرف يفتحونه بلمسة", body: "ختم شمعي أو ظرف يفتحه الضيوف بلمسة، مع صورتك أو الفيديو الخاص بك خلفه." },
        { title: "أغنيتك من اللمسة الأولى", body: "تبدأ الموسيقى الخلفية لحظة فتح الدعوة." },
        { title: "تأكيد الحضور بالأسماء", body: "يؤكد الضيوف حضورهم بأسمائهم وعدد القادمين، مباشرة إلى قائمة ضيوفك." },
        { title: "البرنامج والاتجاهات", body: "برنامج اليوم، وعدّ تنازلي مباشر، والاتجاهات إلى كل مكان بلمسة واحدة." },
        { title: "قائمة الهدايا", body: "روابط قائمة الهدايا أو التفاصيل المصرفية، معروضة مع باقي الدعوة." },
        { title: "بث مباشر", body: "يمكن للأهل والأصدقاء الذين لا يستطيعون السفر مشاهدته مباشرة، مجاناً أو مقابل رسوم." },
        { title: "طلبات الأغاني", body: "يرسل الضيوف الأغاني التي يريدون سماعها مباشرة إلى منسّق الموسيقى (DJ)." },
        { title: "تعارف الضيوف", body: "يتعرّف الضيوف على من يشاركونهم الاهتمامات ويتواصلون من هواتفهم قبل اليوم الموعود." },
        { title: "رسائل صوتية", body: "يمكن للضيوف الذين لا يستطيعون الحضور ترك رسالة صوتية مسجّلة مع ردّهم." },
        { title: "تسجيل الحضور برمز QR", body: "يحصل كل ضيف مؤكَّد على رمز QR لتسجيل حضوره عند الباب." },
        { title: "خمس لغات مع ترجمة بالذكاء الاصطناعي", body: "اكتب الدعوة مرة واحدة بلغتك، ويترجمها الذكاء الاصطناعي بالكامل إلى الإنجليزية أو العربية أو الفرنسية أو الإسبانية أو الأرمنية. ويبدّل الضيوف اللغة من الدعوة نفسها." },
        { title: "مساعد ذكي يملأ البيانات عنك", body: "أخبر المساعد بالأسماء والتاريخ والأماكن، وسيملأ نموذج الدعوة نيابةً عنك." },
      ],
    },
    designs: { title: "تصاميم جاهزة لتصبح لك", body: "اشترِ تصميماً، ثم عدّله بنفسك على Canva.", seeAll: "شاهد كل التصاميم" },
    dashboard: {
      title: "قائمة ضيوفك، تحت السيطرة",
      body: "يصل كل ردّ إلى لوحة التحكم الخاصة بك، لتعرف دائماً أين تقف الأمور.",
      points: [
        "اعرف من فتح الدعوة ومن لم يفتحها بعد",
        "تابع التأكيدات وعدد الحضور مع وصول الردود",
        "خطّط للطاولات وتوزيع المقاعد في القاعة",
        "أرسل لكل ضيف أو عائلة رابطاً شخصياً خاصاً بهم",
      ],
      label: "لوحة التحكم",
      stats: ["المدعوّون", "فتحوها", "سيحضرون"],
      rows: [["عائلة حدّاد", "سيحضرون · 4"], ["ريتا وسامي", "فتحاها"], ["عائلة خوري", "سيحضرون · 3"], ["العمّ جورج", "لم تُفتح بعد"]],
    },
    faq: {
      title: "الأسئلة الشائعة",
      body: "كل ما تحتاج معرفته عن خدمة الدعوات الرقمية لدينا.",
      items: [
        { q: "ما هي الدعوة الرقمية؟", a: "هي دعوة يفتحها ضيوفك على هواتفهم من رابط واحد. يلمسون ظرفاً لفتحه، وفي داخله صورك وموسيقاك والبرنامج والاتجاهات إلى كل مكان وتأكيد الحضور، كلّها في مكان واحد." },
        { q: "لأي مناسبات يمكنني استخدامها؟", a: "حفلات الزفاف وأعياد الميلاد وحفلات الخامسة عشرة والمعموديات وحفلات استقبال المولود وأي مناسبة أخرى. تبدأ كل مناسبة بصفحات جاهزة يمكنك تعديلها كما تشاء." },
        { q: "هل يحتاج ضيوفي إلى تنزيل تطبيق؟", a: "لا. تُفتح الدعوة في المتصفح على أي هاتف، فلا شيء للتثبيت ولا حساب يحتاج الضيوف إلى إنشائه." },
        { q: "كيف أرسلها إلى ضيوفي؟", a: "تحصل على رابط واحد تشاركه عبر واتساب أو إنستغرام أو الرسائل النصية أو البريد الإلكتروني. ويمكنك أيضاً إنشاء رابط شخصي لكل عائلة، ليُسجَّل ردّها باسمها في قائمة ضيوفك." },
        { q: "كيف يعمل تأكيد الحضور؟", a: "يؤكد الضيوف حضورهم بأسمائهم وعدد الأشخاص القادمين. يظهر كل ردّ فوراً في لوحة التحكم الخاصة بك، حيث يمكنك أيضاً معرفة من فتح الدعوة وتحديد موعد نهائي للرد." },
        { q: "هل يمكنني تعديل الدعوة بعد إرسالها؟", a: "نعم. عدّلها في أي وقت واحفظ التغييرات، وسيرى ضيوفك أحدث نسخة على الرابط نفسه." },
        { q: "ما اللغات المتوفرة؟", a: "الإنجليزية والعربية والفرنسية والإسبانية والأرمنية. عندما تضيف لغة، يترجم الذكاء الاصطناعي الدعوة كاملة خلال ثوانٍ، ويمكنك تعديل أي نص بنفسك. ويمكن للضيوف التبديل بين اللغات التي تفعّلها مباشرة من الدعوة." },
        { q: "هل يمكنني إضافة موسيقى وصور وفيديو؟", a: "نعم. أضف موسيقى خلفية تبدأ عند فتح الدعوة، وصورتك أو الفيديو الخاص بك خلف الظرف، وخلفيات بالصور لكل صفحة، وبثاً مباشراً للضيوف الذين لا يستطيعون الحضور." },
        { q: "كيف أشتري تصميماً؟", a: "اختر تصميماً من صفحة التصاميم وادفع عبر الإنترنت. تُعدَّل تصاميم Canva على Canva، أما تصاميم موقعنا فتُعدَّل مباشرة على eInvite.me بعد إنشاء حسابك." },
        { q: "هل يمكنني استرداد المبلغ؟", a: "جميع المدفوعات نهائية وغير قابلة للاسترداد. التصاميم والميزات رقمية وتُسلَّم فوراً، لذا لا يمكننا ردّ المبلغ بعد الدفع. إذا كان هناك ما لا يعمل كما يجب، راسلنا وسنساعدك في إصلاحه." },
        { q: "ماذا يحدث لمعلوماتي؟", a: "نستخدمها فقط لتشغيل دعوتك ومساعدتك، ولا نبيعها أبداً. اقرأ التفاصيل في", privacy: true, privacyLink: "سياسة الخصوصية", privacyAfter: "." },
        { q: "كيف أحصل على المساعدة؟", a: "اضغط على زر الدردشة أسفل أي صفحة للتحدث معنا مباشرة، أو تواصل معنا عبر قسم «تواصل معنا». يسعدنا مساعدتك في كل خطوة." },
      ],
    },
    cta: { title: "جاهزون متى كنت جاهزاً", body: "ابدأ بتصميم تحبه، وأرسله في اليوم نفسه.", create: "أنشئ دعوتك", browse: "تصفّح التصاميم" },
    about: {
      title: "من نحن",
      p1: "eInvite.me استوديو للدعوات الرقمية مقرّه بيروت، لبنان. نؤمن بأن الدعوة هي اللحظة الأولى في كل احتفال، لذلك نصنع دعوات يكون فتحها مميزاً كاليوم نفسه: ظرف يفتحه ضيوفك بلمسة، مع موسيقاك وصورك وكل تفاصيل اليوم في رابط واحد.",
      p2: "سواء كان زفافاً أو عيد ميلاد أو حفلة الخامسة عشرة أو معمودية أو أي مناسبة تخطط لها، نحن هنا لمساعدتك في إنشائها وإرسالها، وتفصلك عنا رسالة واحدة كلما احتجت إلى المساعدة.",
      office: "مكتبنا",
      address: "مكتب 305، برج 44، الدكوانة، بيروت، لبنان",
      openMaps: "افتح في خرائط Google",
      mapTitle: "موقع مكتب eInvite.me",
    },
    contact: {
      title: "تواصل معنا",
      bodyChat: "لديك أسئلة قبل أن تبدأ؟ راسلنا مباشرة، يسعدنا مساعدتك.",
      bodyNoChat: "لديك أسئلة قبل أن تبدأ؟ يسعدنا مساعدتك.",
    },
    footer: { privacy: "سياسة الخصوصية" },
    language: "اللغة",
  },

  fr: {
    nav: { how: "Comment ça marche", features: "Fonctionnalités", designs: "Modèles", blog: "Blog", faq: "FAQ", about: "À propos", contact: "Contact", logIn: "Se connecter", start: "Commencer" },
    hero: {
      eyebrow: "Invitations numériques pour toutes les occasions",
      title: "Une invitation qui s'ouvre comme une vraie enveloppe.",
      body: "Créez une invitation pour votre mariage, votre anniversaire, vos quinze ans ou tout autre événement. Vos invités l'ouvrent d'un geste sur leur téléphone, avec vos photos, votre musique, le programme, les itinéraires et la confirmation de présence, le tout dans un seul lien à partager sur WhatsApp.",
      create: "Créer votre invitation",
      seeDesigns: "Voir les modèles",
      note: "Fonctionne sur tous les téléphones · Rien à télécharger pour les invités",
      phoneLink: "Touchez l'invitation pour l'ouvrir, ou affichez-la en plein écran",
    },
    occasions: {
      title: "Une invitation, pour chaque occasion",
      body: "Chaque occasion commence avec ses propres pages et son programme déjà rédigés, que vous pouvez modifier comme vous le souhaitez.",
      names: { wedding: "Mariage", birthday: "Anniversaire", quinceanera: "Quinceañera", baptism: "Baptême", babyShower: "Baby shower", any: "Tout événement" },
    },
    how: {
      title: "Trois étapes, et c'est parti",
      steps: [
        { title: "Choisissez un modèle", body: "Partez d'un modèle prêt à l'emploi, ou d'une page vierge." },
        { title: "Personnalisez-la", body: "Ajoutez vos noms, photos, musique, le programme de la journée et les lieux, et placez chaque élément exactement où vous le voulez." },
        { title: "Partagez et suivez", body: "Envoyez un seul lien sur WhatsApp. Voyez qui l'a ouvert et qui vient, au fil des réponses." },
      ],
    },
    features: {
      title: "Tout ce dont la journée a besoin, dans un seul lien",
      body: "Chaque page de l'invitation est un moment à part. Affichez celles dont vous avez besoin et masquez les autres.",
      items: [
        { title: "Une enveloppe à ouvrir d'un geste", body: "Un sceau de cire ou une enveloppe que vos invités ouvrent d'un geste, avec votre propre photo ou vidéo derrière." },
        { title: "Votre chanson, dès le premier geste", body: "La musique de fond démarre dès l'ouverture de l'invitation." },
        { title: "Réponses nominatives", body: "Les invités confirment avec leurs noms et le nombre de personnes, directement dans votre liste d'invités." },
        { title: "Programme et itinéraires", body: "Le déroulé de la journée, un compte à rebours en direct et l'itinéraire vers chaque lieu en un geste." },
        { title: "Liste de cadeaux", body: "Liens vers votre liste de cadeaux ou coordonnées bancaires, présentés avec le reste de l'invitation." },
        { title: "Diffusion en direct", body: "La famille et les amis qui ne peuvent pas se déplacer peuvent suivre l'événement en direct, gratuitement ou en payant." },
        { title: "Demandes de chansons", body: "Les invités envoient les chansons qu'ils veulent entendre directement à votre DJ." },
        { title: "Rencontres entre invités", body: "Les invités découvrent ceux qui partagent leurs centres d'intérêt et se connectent depuis leur téléphone avant le jour J." },
        { title: "Messages vocaux", body: "Les invités qui ne peuvent pas venir peuvent vous laisser un message vocal avec leur réponse." },
        { title: "Enregistrement par QR code", body: "Chaque invité confirmé reçoit un QR code pour s'enregistrer à l'entrée." },
        { title: "Cinq langues, traduites par l'IA", body: "Écrivez-la une fois dans votre langue, et l'IA traduit toute l'invitation en anglais, arabe, français, espagnol ou arménien. Les invités changent de langue directement sur l'invitation." },
        { title: "Un assistant IA qui remplit tout", body: "Donnez à l'assistant vos noms, la date et les lieux, et il remplit le formulaire de l'invitation pour vous." },
      ],
    },
    designs: { title: "Des modèles prêts à devenir les vôtres", body: "Achetez un modèle, puis personnalisez-le vous-même dans Canva.", seeAll: "Voir tous les modèles" },
    dashboard: {
      title: "Votre liste d'invités, sous contrôle",
      body: "Chaque réponse arrive dans votre propre tableau de bord, pour savoir à tout moment où en sont les choses.",
      points: [
        "Voyez qui a ouvert l'invitation, et qui ne l'a pas encore fait",
        "Suivez les confirmations et le nombre de personnes au fil des réponses",
        "Organisez les tables et le plan de salle de votre lieu",
        "Envoyez à chaque invité ou famille son propre lien personnel",
      ],
      label: "Tableau de bord",
      stats: ["Invités", "Ouverte", "Présents"],
      rows: [["La famille Haddad", "Présents · 4"], ["Rita & Sami", "Ouverte"], ["La famille Khoury", "Présents · 3"], ["Oncle Georges", "Pas encore ouverte"]],
    },
    faq: {
      title: "Questions fréquentes",
      body: "Tout ce qu'il faut savoir sur notre service d'invitations numériques.",
      items: [
        { q: "Qu'est-ce qu'une invitation numérique ?", a: "C'est une invitation que vos invités ouvrent sur leur téléphone à partir d'un seul lien. Ils touchent une enveloppe pour l'ouvrir, et à l'intérieur se trouvent vos photos, votre musique, le programme, l'itinéraire vers chaque lieu et la confirmation de présence, le tout au même endroit." },
        { q: "Pour quelles occasions puis-je l'utiliser ?", a: "Mariages, anniversaires, quinceañeras, baptêmes, baby showers et tout autre événement. Chaque occasion commence avec ses propres pages déjà rédigées, que vous pouvez modifier comme vous le souhaitez." },
        { q: "Mes invités doivent-ils télécharger une application ?", a: "Non. L'invitation s'ouvre dans le navigateur de n'importe quel téléphone : rien à installer et aucun compte à créer pour les invités." },
        { q: "Comment l'envoyer à mes invités ?", a: "Vous obtenez un seul lien à partager sur WhatsApp, Instagram, par SMS ou par e-mail. Vous pouvez aussi créer un lien personnel pour chaque famille, afin que sa réponse lui soit associée dans votre liste d'invités." },
        { q: "Comment fonctionnent les réponses ?", a: "Les invités confirment avec leurs noms et le nombre de personnes qui viennent. Chaque réponse apparaît immédiatement dans votre tableau de bord, où vous voyez aussi qui a ouvert l'invitation et pouvez fixer une date limite de réponse." },
        { q: "Puis-je modifier l'invitation après l'avoir envoyée ?", a: "Oui. Modifiez-la à tout moment et enregistrez : vos invités verront la dernière version sur le même lien." },
        { q: "Quelles langues sont disponibles ?", a: "Anglais, arabe, français, espagnol et arménien. Quand vous ajoutez une langue, l'IA traduit toute l'invitation en quelques secondes, et vous pouvez toujours modifier n'importe quel texte vous-même. Les invités peuvent passer d'une langue activée à l'autre directement sur l'invitation." },
        { q: "Puis-je ajouter de la musique, des photos et des vidéos ?", a: "Oui. Ajoutez une musique de fond qui démarre à l'ouverture de l'invitation, votre propre photo ou vidéo derrière l'enveloppe, des photos en fond sur chaque page, et une diffusion en direct pour les invités qui ne peuvent pas venir." },
        { q: "Comment acheter un modèle ?", a: "Choisissez-en un sur la page Modèles et payez en ligne. Les modèles Canva se personnalisent dans Canva ; nos modèles web se personnalisent directement sur eInvite.me après la création de votre compte." },
        { q: "Puis-je être remboursé ?", a: "Tous les paiements sont définitifs et non remboursables. Les modèles et fonctionnalités sont numériques et livrés immédiatement : nous ne pouvons donc pas les rembourser une fois payés. Si quelque chose ne fonctionne pas comme prévu, écrivez-nous et nous vous aiderons à le régler." },
        { q: "Que deviennent mes informations ?", a: "Nous les utilisons uniquement pour faire fonctionner votre invitation et vous accompagner, et nous ne les vendons jamais. Lisez les détails dans notre", privacy: true, privacyLink: "Politique de confidentialité", privacyAfter: "." },
        { q: "Comment obtenir de l'aide ?", a: "Touchez le bouton de discussion en bas de n'importe quelle page pour nous parler directement, ou contactez-nous via la section Contact. Nous sommes ravis de vous aider à chaque étape." },
      ],
    },
    cta: { title: "Prêts quand vous l'êtes", body: "Commencez avec un modèle que vous aimez, et envoyez-le le jour même.", create: "Créer votre invitation", browse: "Parcourir les modèles" },
    about: {
      title: "À propos",
      p1: "eInvite.me est un studio d'invitations numériques basé à Beyrouth, au Liban. Nous pensons que l'invitation est le premier moment de chaque célébration ; c'est pourquoi nous créons des invitations aussi spéciales à ouvrir que le jour lui-même : une enveloppe que vos invités ouvrent d'un geste, votre musique, vos photos et tous les détails de la journée dans un seul lien.",
      p2: "Mariage, anniversaire, quinceañera, baptême ou tout autre rassemblement que vous préparez : nous sommes là pour vous aider à la créer et à l'envoyer, et nous ne sommes qu'à un message de vous dès que vous avez besoin d'un coup de main.",
      office: "Notre bureau",
      address: "Bureau 305, Tower 44, Dekweneh, Beyrouth, Liban",
      openMaps: "Ouvrir dans Google Maps",
      mapTitle: "Emplacement du bureau eInvite.me",
    },
    contact: {
      title: "Contactez-nous",
      bodyChat: "Des questions avant de commencer ? Écrivez-nous directement, nous serons ravis de vous aider.",
      bodyNoChat: "Des questions avant de commencer ? Nous serons ravis de vous aider.",
    },
    footer: { privacy: "Politique de confidentialité" },
    language: "Langue",
  },

  es: {
    nav: { how: "Cómo funciona", features: "Funciones", designs: "Diseños", blog: "Blog", faq: "Preguntas", about: "Nosotros", contact: "Contacto", logIn: "Iniciar sesión", start: "Empezar" },
    hero: {
      eyebrow: "Invitaciones digitales para cada ocasión",
      title: "Una invitación que se abre como un sobre de verdad.",
      body: "Crea una invitación para tu boda, tu cumpleaños, tus quince años o cualquier evento. Tus invitados la abren con un toque en su teléfono, con tus fotos, tu música, el programa, las indicaciones y la confirmación de asistencia, todo en un solo enlace que compartes por WhatsApp.",
      create: "Crea tu invitación",
      seeDesigns: "Ver los diseños",
      note: "Funciona en cualquier teléfono · Los invitados no tienen que descargar nada",
      phoneLink: "Toca la invitación para abrirla, o mírala en pantalla completa",
    },
    occasions: {
      title: "Una invitación, para cualquier ocasión",
      body: "Cada ocasión empieza con sus propias páginas y su programa ya escritos, que puedes cambiar como quieras.",
      names: { wedding: "Boda", birthday: "Cumpleaños", quinceanera: "Quinceañera", baptism: "Bautizo", babyShower: "Baby shower", any: "Cualquier evento" },
    },
    how: {
      title: "Tres pasos, y está en camino",
      steps: [
        { title: "Elige un diseño", body: "Empieza con un diseño listo, o con un lienzo en blanco." },
        { title: "Hazla tuya", body: "Añade los nombres, las fotos, la música, el programa del día y los lugares, y coloca cada cosa justo donde quieras." },
        { title: "Comparte y sigue", body: "Envía un solo enlace por WhatsApp. Mira quién la abrió y quién viene a medida que llegan las respuestas." },
      ],
    },
    features: {
      title: "Todo lo que el día necesita, en un solo enlace",
      body: "Cada página de la invitación es un momento propio. Muestra las que necesites y oculta el resto.",
      items: [
        { title: "Un sobre que abren con un toque", body: "Un sello de cera o un sobre que tus invitados abren con un toque, con tu propia foto o video detrás." },
        { title: "Tu canción, desde el primer toque", body: "La música de fondo empieza en cuanto abren la invitación." },
        { title: "Confirmación con nombres", body: "Los invitados confirman con sus nombres y cuántos vienen, directo a tu lista de invitados." },
        { title: "Programa e indicaciones", body: "El programa del día, una cuenta regresiva en vivo e indicaciones a cada lugar con un toque." },
        { title: "Mesa de regalos", body: "Enlaces a tu mesa de regalos o datos bancarios, junto con el resto de la invitación." },
        { title: "Transmisión en vivo", body: "Familiares y amigos que no pueden viajar pueden verla en vivo, gratis o de pago." },
        { title: "Peticiones de canciones", body: "Los invitados envían las canciones que quieren escuchar directamente a tu DJ." },
        { title: "Networking entre invitados", body: "Los invitados descubren a quienes comparten sus intereses y conectan desde su teléfono antes del gran día." },
        { title: "Mensajes de voz", body: "Los invitados que no pueden asistir pueden dejarte un mensaje de voz grabado con su respuesta." },
        { title: "Registro con código QR", body: "Cada invitado confirmado recibe un código QR para registrarse en la entrada." },
        { title: "Cinco idiomas, traducidos con IA", body: "Escríbela una vez en tu idioma y la IA traduce toda la invitación al inglés, árabe, francés, español o armenio. Los invitados cambian de idioma en la propia invitación." },
        { title: "Un asistente con IA que lo completa por ti", body: "Dile al asistente los nombres, la fecha y los lugares, y rellena el formulario de la invitación por ti." },
      ],
    },
    designs: { title: "Diseños listos para hacerlos tuyos", body: "Compra un diseño y personalízalo tú mismo en Canva.", seeAll: "Ver todos los diseños" },
    dashboard: {
      title: "Tu lista de invitados, bajo control",
      body: "Cada respuesta llega a tu propio panel, para que siempre sepas cómo van las cosas.",
      points: [
        "Mira quién abrió la invitación y quién todavía no",
        "Sigue las confirmaciones y el número de asistentes a medida que llegan",
        "Organiza las mesas y la distribución de asientos del lugar",
        "Envía a cada invitado o familia su propio enlace personal",
      ],
      label: "Panel",
      stats: ["Invitados", "Abierta", "Asisten"],
      rows: [["Familia Haddad", "Asisten · 4"], ["Rita y Sami", "Abierta"], ["Familia Khoury", "Asisten · 3"], ["Tío Georges", "Sin abrir todavía"]],
    },
    faq: {
      title: "Preguntas frecuentes",
      body: "Todo lo que necesitas saber sobre nuestro servicio de invitaciones digitales.",
      items: [
        { q: "¿Qué es una invitación digital?", a: "Es una invitación que tus invitados abren en su teléfono desde un solo enlace. Tocan un sobre para abrirla y dentro están tus fotos, tu música, el programa, las indicaciones a cada lugar y la confirmación de asistencia, todo en un mismo sitio." },
        { q: "¿Para qué ocasiones puedo usarla?", a: "Bodas, cumpleaños, quinceañeras, bautizos, baby showers y cualquier otro evento. Cada ocasión empieza con sus propias páginas ya escritas, que puedes cambiar como quieras." },
        { q: "¿Mis invitados tienen que descargar una aplicación?", a: "No. La invitación se abre en el navegador de cualquier teléfono, así que no hay nada que instalar ni cuentas que crear." },
        { q: "¿Cómo se la envío a mis invitados?", a: "Recibes un solo enlace para compartir por WhatsApp, Instagram, SMS o correo electrónico. También puedes crear un enlace personal para cada familia, para que su respuesta quede asociada a ellos en tu lista de invitados." },
        { q: "¿Cómo funcionan las confirmaciones?", a: "Los invitados confirman con sus nombres y cuántas personas vienen. Cada respuesta aparece al instante en tu panel, donde también ves quién abrió la invitación y puedes fijar una fecha límite para responder." },
        { q: "¿Puedo cambiar la invitación después de enviarla?", a: "Sí. Edítala cuando quieras y guarda; tus invitados verán la última versión en el mismo enlace." },
        { q: "¿Qué idiomas hay disponibles?", a: "Inglés, árabe, francés, español y armenio. Cuando añades un idioma, la IA traduce toda la invitación en segundos, y puedes seguir editando cualquier texto a mano. Los invitados pueden cambiar entre los idiomas que actives, en la propia invitación." },
        { q: "¿Puedo añadir música, fotos y video?", a: "Sí. Añade música de fondo que empieza al abrir la invitación, tu propia foto o video detrás del sobre, fotos de fondo en cada página y una transmisión en vivo para quienes no puedan asistir." },
        { q: "¿Cómo compro un diseño?", a: "Elige uno en la página de Diseños y paga en línea. Los diseños de Canva se personalizan en Canva; nuestros diseños web se personalizan directamente en eInvite.me después de crear tu cuenta." },
        { q: "¿Puedo pedir un reembolso?", a: "Todos los pagos son definitivos y no reembolsables. Los diseños y las funciones son digitales y se entregan al instante, por lo que no podemos reembolsarlos una vez pagados. Si algo no funciona como debería, escríbenos y te ayudaremos a solucionarlo." },
        { q: "¿Qué pasa con mi información?", a: "Solo la usamos para hacer funcionar tu invitación y ayudarte, y nunca la vendemos. Lee los detalles en nuestra", privacy: true, privacyLink: "Política de privacidad", privacyAfter: "." },
        { q: "¿Cómo consigo ayuda?", a: "Toca el botón de chat en la parte inferior de cualquier página para hablar con nosotros directamente, o contáctanos en la sección de Contacto. Estaremos encantados de ayudarte en cada paso." },
      ],
    },
    cta: { title: "Listos cuando tú lo estés", body: "Empieza con un diseño que te encante y envíalo el mismo día.", create: "Crea tu invitación", browse: "Explorar los diseños" },
    about: {
      title: "Sobre nosotros",
      p1: "eInvite.me es un estudio de invitaciones digitales con sede en Beirut, Líbano. Creemos que la invitación es el primer momento de cada celebración, por eso creamos invitaciones que se sienten tan especiales al abrirlas como el propio día: un sobre que tus invitados abren con un toque, tu música, tus fotos y todos los detalles del día en un solo enlace.",
      p2: "Bodas, cumpleaños, quinceañeras, bautizos o cualquier reunión que estés preparando: estamos aquí para ayudarte a crearla y enviarla, y estamos a un mensaje de distancia cuando necesites una mano.",
      office: "Nuestra oficina",
      address: "Oficina 305, Tower 44, Dekweneh, Beirut, Líbano",
      openMaps: "Abrir en Google Maps",
      mapTitle: "Ubicación de la oficina de eInvite.me",
    },
    contact: {
      title: "Contáctanos",
      bodyChat: "¿Tienes preguntas antes de empezar? Escríbenos directamente, estaremos encantados de ayudarte.",
      bodyNoChat: "¿Tienes preguntas antes de empezar? Estaremos encantados de ayudarte.",
    },
    footer: { privacy: "Política de privacidad" },
    language: "Idioma",
  },

  hy: {
    nav: { how: "Ինչպես է աշխատում", features: "Հնարավորություններ", designs: "Դիզայններ", blog: "Բլոգ", faq: "Հարցեր", about: "Մեր մասին", contact: "Կապ", logIn: "Մուտք", start: "Սկսել" },
    hero: {
      eyebrow: "Թվային հրավերներ ցանկացած առիթի համար",
      title: "Հրավեր, որը բացվում է իսկական ծրարի պես։",
      body: "Ստեղծեք հրավեր ձեր հարսանիքի, ծննդյան տոնի, տասնհինգամյակի կամ ցանկացած միջոցառման համար։ Հյուրերը այն բացում են իրենց հեռախոսում մեկ հպումով՝ ձեր լուսանկարներով, երաժշտությամբ, օրվա ծրագրով, ուղղություններով և մասնակցության հաստատմամբ, ամբողջը մեկ հղումով, որը կիսվում եք WhatsApp-ով։",
      create: "Ստեղծեք ձեր հրավերը",
      seeDesigns: "Տեսնել դիզայնները",
      note: "Աշխատում է ցանկացած հեռախոսում · Հյուրերը ոչինչ ներբեռնելու կարիք չունեն",
      phoneLink: "Հպեք հրավերին՝ այն բացելու համար, կամ դիտեք ամբողջ էկրանով",
    },
    occasions: {
      title: "Մեկ հրավեր՝ ցանկացած առիթի համար",
      body: "Յուրաքանչյուր առիթ սկսվում է իր պատրաստի էջերով և ծրագրով, որոնք կարող եք փոխել ըստ ձեր ցանկության։",
      names: { wedding: "Հարսանիք", birthday: "Ծննդյան տոն", quinceanera: "Տասնհինգամյակ", baptism: "Մկրտություն", babyShower: "Baby shower", any: "Ցանկացած միջոցառում" },
    },
    how: {
      title: "Երեք քայլ, և այն ճանապարհին է",
      steps: [
        { title: "Ընտրեք դիզայն", body: "Սկսեք պատրաստի դիզայնից կամ դատարկ էջից։" },
        { title: "Դարձրեք այն ձերը", body: "Ավելացրեք անունները, լուսանկարները, երաժշտությունը, օրվա ծրագիրը և վայրերը, և տեղադրեք ամեն ինչ ճիշտ այնտեղ, որտեղ ցանկանում եք։" },
        { title: "Կիսվեք և հետևեք", body: "Ուղարկեք մեկ հղում WhatsApp-ով։ Տեսեք, թե ով է այն բացել և ով է գալու՝ պատասխանների ստացմանը զուգընթաց։" },
      ],
    },
    features: {
      title: "Այն ամենը, ինչ պետք է օրվա համար, մեկ հղումով",
      body: "Հրավերի յուրաքանչյուր էջ առանձին պահ է։ Ցուցադրեք ձեզ անհրաժեշտները և թաքցրեք մնացածը։",
      items: [
        { title: "Ծրար, որը բացում են հպումով", body: "Մոմե կնիք կամ ծրար, որը հյուրերը բացում են հպումով, ձեր սեփական լուսանկարով կամ տեսանյութով ետևում։" },
        { title: "Ձեր երգը՝ առաջին հպումից", body: "Ֆոնային երաժշտությունը սկսվում է հրավերը բացելու պահին։" },
        { title: "Հաստատում անուններով", body: "Հյուրերը հաստատում են իրենց անուններով և թե քանի հոգի են գալու՝ ուղիղ ձեր հյուրերի ցուցակում։" },
        { title: "Ծրագիր և ուղղություններ", body: "Օրվա ժամանակացույցը, ուղիղ հետհաշվարկ և մեկ հպումով ուղղություններ դեպի յուրաքանչյուր վայր։" },
        { title: "Նվերների ցուցակ", body: "Նվերների ցուցակի հղումներ կամ բանկային տվյալներ՝ հրավերի մնացած մասի հետ միասին։" },
        { title: "Ուղիղ հեռարձակում", body: "Ընտանիքն ու ընկերները, ովքեր չեն կարող գալ, կարող են դիտել այն ուղիղ եթերում՝ անվճար կամ վճարովի։" },
        { title: "Երգերի պատվերներ", body: "Հյուրերն իրենց ուզած երգերն ուղարկում են անմիջապես ձեր DJ-ին։" },
        { title: "Հյուրերի ծանոթություն", body: "Հյուրերը գտնում են նույն հետաքրքրություններն ունեցողներին և կապվում նրանց հետ իրենց հեռախոսից՝ նախքան տոնը։" },
        { title: "Ձայնային հաղորդագրություններ", body: "Հյուրերը, ովքեր չեն կարող գալ, կարող են ձեզ ձայնագրված հաղորդագրություն թողնել իրենց պատասխանի հետ։" },
        { title: "Մուտք QR կոդով", body: "Յուրաքանչյուր հաստատված հյուր ստանում է QR կոդ՝ մուտքի մոտ գրանցվելու համար։" },
        { title: "Հինգ լեզու՝ AI թարգմանությամբ", body: "Գրեք այն մեկ անգամ ձեր լեզվով, և AI-ն ամբողջ հրավերը կթարգմանի անգլերեն, արաբերեն, ֆրանսերեն, իսպաներեն կամ հայերեն։ Հյուրերը լեզուն փոխում են հենց հրավերում։" },
        { title: "AI օգնական, որը լրացնում է ձեր փոխարեն", body: "Ասեք օգնականին անունները, ամսաթիվը և վայրերը, և այն կլրացնի հրավերի ձևը ձեր փոխարեն։" },
      ],
    },
    designs: { title: "Պատրաստի դիզայններ, որոնք կդառնան ձերը", body: "Գնեք դիզայն, ապա անհատականացրեք այն ինքներդ Canva-ում։", seeAll: "Տեսնել բոլոր դիզայնները" },
    dashboard: {
      title: "Ձեր հյուրերի ցուցակը՝ վերահսկողության տակ",
      body: "Յուրաքանչյուր պատասխան հասնում է ձեր վահանակ, որպեսզի միշտ իմանաք, թե ինչպես են ընթանում գործերը։",
      points: [
        "Տեսեք, թե ով է բացել հրավերը և ով՝ դեռ ոչ",
        "Հետևեք հաստատումներին և մասնակիցների թվին՝ պատասխանների ստացմանը զուգընթաց",
        "Պլանավորեք սեղանները և դահլիճի նստատեղերի դասավորությունը",
        "Ուղարկեք յուրաքանչյուր հյուրի կամ ընտանիքի իր անձնական հղումը",
      ],
      label: "Վահանակ",
      stats: ["Հրավիրված", "Բացել են", "Գալու են"],
      rows: [["Հադադների ընտանիք", "Գալու են · 4"], ["Ռիտա և Սամի", "Բացել են"], ["Խուրիների ընտանիք", "Գալու են · 3"], ["Քեռի Ժորժ", "Դեռ չի բացել"]],
    },
    faq: {
      title: "Հաճախ տրվող հարցեր",
      body: "Այն ամենը, ինչ պետք է իմանաք մեր թվային հրավերների ծառայության մասին։",
      items: [
        { q: "Ի՞նչ է թվային հրավերը", a: "Դա հրավեր է, որը հյուրերը բացում են իրենց հեռախոսում մեկ հղումից։ Նրանք հպում են ծրարին՝ այն բացելու համար, իսկ ներսում ձեր լուսանկարներն են, երաժշտությունը, ծրագիրը, ուղղությունները դեպի յուրաքանչյուր վայր և մասնակցության հաստատումը՝ բոլորը մեկ տեղում։" },
        { q: "Ո՞ր առիթների համար կարող եմ այն օգտագործել", a: "Հարսանիքներ, ծննդյան տոներ, տասնհինգամյակներ, մկրտություններ, baby shower-ներ և ցանկացած այլ միջոցառում։ Յուրաքանչյուր առիթ սկսվում է իր պատրաստի էջերով, որոնք կարող եք փոխել ըստ ցանկության։" },
        { q: "Պե՞տք է արդյոք հյուրերը հավելված ներբեռնեն", a: "Ոչ։ Հրավերը բացվում է ցանկացած հեռախոսի բրաուզերում, ուստի տեղադրելու ոչինչ չկա, և հյուրերը հաշիվ ստեղծելու կարիք չունեն։" },
        { q: "Ինչպե՞ս ուղարկել այն հյուրերին", a: "Դուք ստանում եք մեկ հղում՝ կիսվելու WhatsApp-ով, Instagram-ով, SMS-ով կամ էլ. փոստով։ Կարող եք նաև յուրաքանչյուր ընտանիքի համար ստեղծել անձնական հղում, որպեսզի նրանց պատասխանը կապվի նրանց հետ ձեր հյուրերի ցուցակում։" },
        { q: "Ինչպե՞ս է աշխատում մասնակցության հաստատումը", a: "Հյուրերը հաստատում են իրենց անուններով և թե քանի հոգի են գալու։ Յուրաքանչյուր պատասխան անմիջապես հայտնվում է ձեր վահանակում, որտեղ կարող եք նաև տեսնել, թե ով է բացել հրավերը, և սահմանել պատասխանելու վերջնաժամկետ։" },
        { q: "Կարո՞ղ եմ փոխել հրավերը այն ուղարկելուց հետո", a: "Այո։ Խմբագրեք այն ցանկացած պահի և պահպանեք․ հյուրերը կտեսնեն վերջին տարբերակը նույն հղումով։" },
        { q: "Ի՞նչ լեզուներ կան", a: "Անգլերեն, արաբերեն, ֆրանսերեն, իսպաներեն և հայերեն։ Երբ լեզու եք ավելացնում, AI-ն վայրկյանների ընթացքում թարգմանում է ամբողջ հրավերը, և դուք միշտ կարող եք ձեռքով խմբագրել ցանկացած տեքստ։ Հյուրերը կարող են փոխել ձեր միացրած լեզուները հենց հրավերում։" },
        { q: "Կարո՞ղ եմ ավելացնել երաժշտություն, լուսանկարներ և տեսանյութ", a: "Այո։ Ավելացրեք ֆոնային երաժշտություն, որը սկսվում է հրավերը բացելիս, ձեր լուսանկարը կամ տեսանյութը ծրարի ետևում, լուսանկարային ֆոներ յուրաքանչյուր էջում և ուղիղ հեռարձակում այն հյուրերի համար, ովքեր չեն կարող ներկա լինել։" },
        { q: "Ինչպե՞ս գնել դիզայն", a: "Ընտրեք այն Դիզայններ էջում և վճարեք առցանց։ Canva-ի դիզայնները անհատականացվում են Canva-ում, իսկ մեր կայքի դիզայնները՝ անմիջապես eInvite.me-ում՝ ձեր հաշիվը ստեղծելուց հետո։" },
        { q: "Կարո՞ղ եմ գումարը հետ ստանալ", a: "Բոլոր վճարումները վերջնական են և վերադարձման ենթակա չեն։ Դիզայններն ու հնարավորությունները թվային են և տրամադրվում են անմիջապես, ուստի վճարումից հետո չենք կարող գումարը վերադարձնել։ Եթե ինչ-որ բան չի աշխատում այնպես, ինչպես պետք է, գրեք մեզ, և մենք կօգնենք շտկել այն։" },
        { q: "Ի՞նչ է լինում իմ տվյալների հետ", a: "Մենք դրանք օգտագործում ենք միայն ձեր հրավերն աշխատեցնելու և ձեզ օգնելու համար և երբեք չենք վաճառում։ Մանրամասները՝", privacy: true, privacyLink: "Գաղտնիության քաղաքականություն", privacyAfter: " էջում։" },
        { q: "Ինչպե՞ս ստանալ օգնություն", a: "Հպեք զրույցի կոճակին ցանկացած էջի ներքևում՝ մեզ հետ անմիջապես խոսելու համար, կամ կապվեք մեզ հետ «Կապ» բաժնի միջոցով։ Ուրախ կլինենք օգնել ձեզ յուրաքանչյուր քայլում։" },
      ],
    },
    cta: { title: "Պատրաստ ենք, երբ դուք պատրաստ եք", body: "Սկսեք ձեր սիրած դիզայնով և ուղարկեք այն նույն օրը։", create: "Ստեղծեք ձեր հրավերը", browse: "Դիտել դիզայնները" },
    about: {
      title: "Մեր մասին",
      p1: "eInvite.me-ն թվային հրավերների ստուդիա է Բեյրութում, Լիբանան։ Մենք հավատում ենք, որ հրավերը յուրաքանչյուր տոնի առաջին պահն է, ուստի ստեղծում ենք հրավերներ, որոնց բացելը նույնքան հատուկ է, որքան հենց տոնը՝ ծրար, որը հյուրերը բացում են հպումով, ձեր երաժշտությունը, լուսանկարները և օրվա բոլոր մանրամասները մեկ հղումով։",
      p2: "Հարսանիք, ծննդյան տոն, տասնհինգամյակ, մկրտություն կամ ցանկացած հավաքույթ, որ պլանավորում եք՝ մենք այստեղ ենք, որպեսզի օգնենք ստեղծել և ուղարկել այն, և մեզանից բաժանված եք ընդամենը մեկ հաղորդագրությամբ, երբ օգնության կարիք ունենաք։",
      office: "Մեր գրասենյակը",
      address: "Գրասենյակ 305, Tower 44, Դեկվանե, Բեյրութ, Լիբանան",
      openMaps: "Բացել Google Maps-ում",
      mapTitle: "eInvite.me գրասենյակի գտնվելու վայրը",
    },
    contact: {
      title: "Կապ մեզ հետ",
      bodyChat: "Հարցեր ունե՞ք նախքան սկսելը։ Գրեք մեզ անմիջապես՝ ուրախ կլինենք օգնել։",
      bodyNoChat: "Հարցեր ունե՞ք նախքան սկսելը։ Ուրախ կլինենք օգնել։",
    },
    footer: { privacy: "Գաղտնիության քաղաքականություն" },
    language: "Լեզու",
  },
};
